# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec7b63104d1da2dd6b663fa8b70e89a77996b89c3e4fb981dfd682ea1b026fca5161165e840519347f2e4bfbe30bcb3fca87a3ba39dbd036c58c20a003e1ebe

test:
  secret_key_base: 635c96578f645a5ca2600d87ca62e57c73d193605a0361b481be542f5f0cd4e5e7cef315b6b793a8c29c9d6f4c7d221415b476e31cc109eb078505ff13dcaead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
